export default {
   miwisKategoria: state => state.miwis_kategoria,
   xs: state => state.xs,
   gfdu: state => state.gfdu,
   ekspozicia: state => state.ekspozicia,
   dakaneba: state => state.dakaneba,
   eroziisSaxe: state => state.eroziis_saxe,
   eroziisXarisxi: state => state.eroziis_xarisxi,
   szd: state => state.szd,
   dakanebisName: state => state.dakanebisName,
   iarusi: state => state.iarusi,
   sixshire: state => state.sixshire,
   saxeoba: state => state.saxeoba,
   xnovaneba: state => state.xnovaneba,
   simagle: state => state.simagle,
   diametri: state => state.diametri,
   gonisdzieba_1: state => state.gonisdzieba_1,
   adgilsamyofelisTipi: state => state.adgilsamyofelis_tipi,
   boniteti: state => state.boniteti,
   tkisTipi: state => state.tkis_tipi,
   martvisOrgano: state => state.martvis_organo,
   administracia: state => state.administracia,
   // სატყეო უბანი
   kaxetiSatkeoUbani: state => state.kaxeti_satkeo_ubani,
   kvemoKartliSatkeoUbani: state => state.kvemo_kartli_satkeo_ubani,
   shidaKartliSatkeoUbani: state => state.shida_kartli_satkeo_ubani,
   mcxetaMtianetiSatkeoUbani: state => state.mcxeta_mtianeti_satkeo_ubani,
   imeretiSatkeoUbani: state => state.imereti_satkeo_ubani,
   samegreloZemoSvanetiSatkeoUbani: state => state.samegrelo_zemo_svaneti_satkeo_ubani,
   samcxeJavaxetiSatkeoUbani: state => state.samcxe_javaxeti,
   rachaLechxumiKvemoSvanetiSatkeoUbani: state => state.racha_lechxumi_kvemo_svaneti_satkeo_ubani,
   guriaSatkeoUbani: state => state.guria_satkeo_ubani,
   // კახეთი
   sagarejoSatkeo: state => state.sagarejo_satkeo,
   gurjaaniSatkeo: state => state.gurjaani_satkeo,
   lagodexiDedoflisWkaroSignaxiSatkeo: state => state.lagodexi_dedofliswkaro_signaxi_satkeo,
   kvareliSatkeo: state => state.kvareli_satkeo,
   telaviSatkeo: state => state.telavi_satkeo,
   axmetaSatkeo: state => state.axmeta_satkeo,
   // ქვემო ქართლი
   bolnisiDmanisiSatkeo: state => state.bolnisi_dmanisi_satkeo,
   gardabaniMarneuliSatkeo: state => state.gardabani_marneuli_satkeo,
   walkaTetriwkaroSatkeo: state => state.walka_tetriwkaro_satkeo,
   // შიდა ქართლი
   goriSatkeo: state => state.gori_satkeo,
   kaspiSatkeo: state => state.kaspi_satkeo,
   kareliSatkeo: state => state.kareli_satkeo,
   xashuriSatkeo: state => state.xashuri_satkeo,
   // მცხეთა-მთიანეთი
   mcxetaSatkeo: state => state.mcxeta_satkeo,
   tianetiSatkeo: state => state.tianeti_satkeo,
   barisaxoSatkeo: state => state.barisaxo_satkeo,
   fasanauriSatkeo: state => state.fasanauri_satkeo,
   // იმერეთი
   xoniWkaltuboSatkeo: state => state.xoni_wkaltubo_satkeo,
   vaniBagdatiSatkeo: state => state.vani_bagdati_satkeo,
   chiaturaSatkeo: state => state.chiatura_satkeo,
   sachxereSatkeo: state => state.sachxere_satkeo,
   tkibuliSatkeo: state => state.tkibuli_satkeo,
   zestafoniSatkeo: state => state.zestafoni_satkeo,
   xaragauliSatkeo: state => state.xaragauli_satkeo,
   // სამეგრელო-ზემო სვანეთი
   mestiaSatkeo: state => state.mestia_satkeo,
   xaishiSatkeo: state => state.xaishi_satkeo,
   kolxetiSatkeo: state => state.kolxeti_satkeo,
   chkorowkuSatkeo: state => state.chkorowku_satkeo,
   walenjixaSatkeo: state => state.walenjixa_satkeo,
   martviliSatkeo: state => state.martvili_satkeo,
   // სამცხე ჯავახეთი
   borjomiSatkeo: state => state.borjomi_satkeo,
   bakurianiSatkeo: state => state.bakuriani_satkeo,
   axalcixeSatkeo: state => state.axalcixe_satkeo,
   aspindaAxalcixeSatkeo: state => state.aspindze_axalkalaki_satkeo,
   adigeniSatkeo: state => state.adigeni_satkeo,
   // რაჭა-ლეჩხუმი ქვემო სვანეთი
   ambrolauriSatkeo: state => state.ambrolauri_satkeo,
   oniSatkeo: state => state.oni_satkeo,
   cageriSatkeo: state => state.cageri_satkeo,
   lentexiSatkeo: state => state.lentexi_satkeo,
   // გურია
   choxatauriSatkeo: state => state.choxatauri_satkeo,
   ozurgetiSatkeo: state => state.ozurgeti_satkeo,
   lanchxutiSatkeo: state => state.lanchxuti_satkeo,
}